apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdk 36
    defaultConfig {
        namespace "com.onekosmos.blockidsample"
        applicationId "com.onekosmos.blockid.poc"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.30.60" + "." + getCurrentTimestampHexValue()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('android_blockidsample_keystore.jks')
            storePassword System.getenv("DEMO_STORE_PASSWORD") ?: ""
            keyAlias System.getenv("DEMO_KEY_ALIAS") ?: ""
            keyPassword System.getenv("DEMO_KEY_PASSWORD") ?: ""
        }
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        exclude 'META-INF/rxjava.properties'
        exclude 'lib/x86_64/darwin/libscrypt.dylib'
        exclude 'lib/x86_64/freebsd/libscrypt.so'
        exclude 'lib/x86_64/linux/libscrypt.so'
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/LICENSE.md'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE.md'
        exclude 'AndroidManifest.xml'
        exclude 'META-INF/FastDoubleParser-LICENSE'
        exclude 'META-INF/FastDoubleParser-NOTICE'
        exclude 'META-INF/DISCLAIMER'
        exclude 'META-INF/io.netty.versions.properties'
    }
}

String getCurrentTimestampHexValue() {
    //get current date of build as hex of (current time in seconds)
    Date date = new Date()
    long timestamp = (date.getTime() / 1000)
    String hexVal = Long.toHexString(timestamp)
    println("HEX VALUE--" + hexVal.toUpperCase())
    return hexVal.toUpperCase()
}

configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.bouncycastle') {
            details.useVersion '1.84'
        }
        // MOB-7221 - Fix Jackson CVEs (transitive via web3j)
        if (details.requested.group == 'com.fasterxml.jackson.core') {
            details.useVersion '2.19.2'
        }
    }
}

dependencies {
    //The default toolchain implements the new language features by performing bytecode
    // transformations, called desugar
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.14.0'

    // Secure  Shared preference
    implementation 'androidx.security:security-crypto:1.1.0'

    // Network Call
    implementation 'com.github.amitshekhariitbhu.Fast-Android-Networking:android-networking:1.0.4'

    //Location
    implementation 'com.google.android.gms:play-services-location:21.3.0'

    // Firebase Crashlytics
    // Import the BoM for the Firebase platform
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation platform('com.google.firebase:firebase-bom:34.14.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    // BlockID SDK
    implementation 'com.onekosmos.blockid.sdk:blockidsdk:1.30.60.dev.6A8840AF'
}
